apiVersion: v1
kind: Service
metadata:
  name: tournament-api-service
spec:
  selector:
    app: tournament-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
