name: ðŸš€ Deploy Tournament API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¦ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ§± Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸ”‘ Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ðŸ³ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: jonnyhdz/tournament-api:latest

      - name: âš™ï¸ Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: ðŸ“ Configure Kubernetes access
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl config use-context docker-desktop

      - name: ðŸš€ Apply Kubernetes manifests
        run: |
          kubectl apply -f backend/k8s/secret.yaml
          kubectl apply -f backend/k8s/deployment.yaml
          kubectl apply -f backend/k8s/service.yaml
          kubectl rollout restart deployment tournament-api-deployment
